// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp2il37_EE75Bcm0Aoe7lxmSwYT0rS9G0',
    appId: '1:159767365646:web:75b840c730c090d99ad45f',
    messagingSenderId: '159767365646',
    projectId: 'koinonia-90a79',
    authDomain: 'koinonia-90a79.firebaseapp.com',
    storageBucket: 'koinonia-90a79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvdpb0TLHr5uEhZKHUZx2XZ507ByXQJt8',
    appId: '1:159767365646:android:63dfc02e193b25809ad45f',
    messagingSenderId: '159767365646',
    projectId: 'koinonia-90a79',
    storageBucket: 'koinonia-90a79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADvVrFV71WQoaCydElEZbJMY1EO-tYHEQ',
    appId: '1:159767365646:ios:f3b7c7fe57a1a9889ad45f',
    messagingSenderId: '159767365646',
    projectId: 'koinonia-90a79',
    storageBucket: 'koinonia-90a79.firebasestorage.app',
    iosBundleId: 'com.example.koinonia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADvVrFV71WQoaCydElEZbJMY1EO-tYHEQ',
    appId: '1:159767365646:ios:f3b7c7fe57a1a9889ad45f',
    messagingSenderId: '159767365646',
    projectId: 'koinonia-90a79',
    storageBucket: 'koinonia-90a79.firebasestorage.app',
    iosBundleId: 'com.example.koinonia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp2il37_EE75Bcm0Aoe7lxmSwYT0rS9G0',
    appId: '1:159767365646:web:8c1323ae2f63db859ad45f',
    messagingSenderId: '159767365646',
    projectId: 'koinonia-90a79',
    authDomain: 'koinonia-90a79.firebaseapp.com',
    storageBucket: 'koinonia-90a79.firebasestorage.app',
  );
}
